# Dockerfile for NGINX reverse proxy
FROM nginx:stable-alpine3.20

# Copy Nginx template
COPY nginx/templates /etc/nginx/templates/
ENV NGINX_PORT=80
ENV NEXTJS_APP_URL=localhost
ENV NEXTJS_APP_PORT=3000
ENV API_BACKEND_URL=localhost
ENV API_BACKEND_PORT=4000

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]