# ----------- Stage 1: Builder Stage ------------
FROM ubuntu:22.04 AS builder

USER root

# Install common dependencies
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    unzip \
    git \
    gnupg \
    ca-certificates \
    nodejs \
    npm \
    jq \
    && rm -rf /var/lib/apt/lists/*

# --- AWS CLI v2 ---
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && ./aws/install -i /aws-cli -b /aws-cli-bin && \
    rm -rf awscliv2.zip aws

# --- kubectl v1.30.0 ---
RUN curl -Lo /kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.0/2023-11-17/bin/linux/amd64/kubectl && \
    chmod +x /kubectl

# --- Trivy ---
RUN wget https://github.com/aquasecurity/trivy/releases/download/v0.60.0/trivy_0.60.0_Linux-64bit.deb && \
    dpkg -x trivy_0.60.0_Linux-64bit.deb /trivy && \
    rm trivy_0.60.0_Linux-64bit.deb


# --- SonarQube Scanner ---
RUN curl -Lo sonarqube.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip \
    && unzip sonarqube.zip && mv sonar-scanner-5.0.1.3006-linux /sonar-scanner \
    && rm sonarqube.zip


# ----------- Stage 2: Final Jenkins Agent Image ------------
FROM jenkins/inbound-agent:latest

USER root

# Install docker client & runtime dependencies
RUN apt-get update && apt-get install -y \
    docker.io \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Copy binaries from builder
COPY --from=builder /aws-cli /aws-cli
COPY --from=builder /aws-cli-bin/aws /usr/local/bin/aws
COPY --from=builder /kubectl /usr/local/bin/kubectl
COPY --from=builder /trivy/usr/bin/trivy /usr/local/bin/trivy
COPY --from=builder /sonar-scanner /opt/sonar-scanner


# Link sonar-scanner to PATH
RUN ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner

# Docker group for Jenkins user
RUN usermod -aG docker jenkins

USER jenkins